задание по кнопкам
js-tasks-ru/htmlcss-20220414_parfenov-v pull request #4
Opened 2022-04-23 20:01 UTC by Valery1971

2022-04-23 20:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-23 20:23 UTC, GSemikozov requested changes

2022-04-23 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.body {
отсюда и до 24 строки - это вспомогательные стили для внешнего позиционирования сетки из кнопок - такие стили ни в коем случае не оформляем в файле стилей конкретного блока; здесь - только .button + его элементы и модификаторы. А вот эти вспомогательные стили - поскольку они нужно только для размещения примера реализации - можно оформить прямо в хтмл странице в теге style

2022-04-23 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +width: 189px;
ширину жестко иксировать не надо

2022-04-23 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +left: 0px;
top + left - свойства которые касаются внешнего позиционирования, мы их на уровне блока не задаем, а значит и здесь их не нужно сбрасывать

2022-04-23 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
модификаторы пишутся через 1 нижнее подчеркивание - нужно везде поправить

2022-04-23 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +border-radius: 8px;
поскольку ниже используем border - лучше сразу задать box-sizing: border-box

2022-04-23 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary-hover:hover {
одновременно и класс и псевдо-класс? если есть встроенный псевдо-класс, который при этом будет работать без необходимости применять js (в случае с классом - его надо динамически навешивать при ховере через js) - то использовать вместо него классы состояний будет ошибкой. Достаточно так: .button_primary:hover. И ниже то же самое

2022-04-23 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-disabled {
.buton:disabled

2022-04-23 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
+ pointer-events: none

2022-04-23 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__title {
.button__text

2022-04-23 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +color: #FFFFFF;
кстати, все цвета проставляем из css-переменных

2022-04-23 20:23 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__title-alternate {
если это модификатор элемента, то .button__text_alternate

2022-04-24 04:59 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +.body {
ок

2022-04-24 05:06 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +left: 0px;
ок

2022-04-24 05:06 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +width: 189px;
так если поставить max-width то кнопки встанут по ширине внутреннего содержания.
Как правильно? пока этот пункт не изменил

2022-04-24 05:12 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +.button__primary {
исправил

2022-04-24 05:19 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +border-radius: 8px;
ок

2022-04-24 05:32 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +.button__title {
ок

2022-04-24 05:34 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +.button__title-alternate {
исправил

2022-04-24 10:36 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +.button-disabled {
разобрался

2022-04-24 10:37 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +color: #FFFFFF;
исправил

2022-04-24 10:39 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
ок

2022-04-24 10:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-24 18:09 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +width: 189px;
хотя бы min-width. Но в идеале - вообще явно не задавать, пусть ширина определяется внутренним содержимым

2022-04-25 10:22 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +width: 189px;
ок

2022-04-25 10:23 UTC, Valery1971 commented on 03-lection1/01-button/button.css
> +.button__primary-hover:hover {
я это раньше исправил, изначально не разобрался с псевдоклассами

2022-04-25 16:06 UTC, GSemikozov approved these changes

2022-04-25 16:06 UTC, merged